@startuml
skinparam ParticipantBackgroundColor #7FFFD4

actor Пользователь
participant "Клиентская игра" as Game
participant "Кэш" as Cache
participant "Игровой сервер" as Server
participant "База данных" as DB

Пользователь -> Game: Открыть магазин и выбрать меч
Game -> Cache: Проверить наличие данных о мечах в кэше
alt Данные в кэше есть
    Cache -> Game: Вернуть данные о мечах
else Данных в кэше нет
    Game -> Server: Запросить данные о мечах [WebSocket]
    Server -> DB: Запросить данные о мечах
    DB -> Server: Вернуть данные о мечах
    Server -> Cache: Сохранить данные о мечах в кэше
    Server -> Game: Отправить данные о мечах [WebSocket]
end
Game -> Пользователь: Отобразить данные о мечах

Пользователь -> Game: Выбрать меч и инициировать покупку
alt Внутренней валюты достаточно
    Game -> Server: Запросить покупку меча [WebSocket]
    Server -> DB: Проверить наличие меча и внутренней валюты у пользователя
    DB -> Server: Подтверждение наличия внутренней валюты и меча
    Server -> DB: Обновить данные (вычесть внутреннюю валюту, добавить меч в инвентарь)
    DB -> Server: Подтверждение обновления данных
    Server -> Cache: Обновить кэш с новыми данными
    Server -> Game: Подтверждение успешной покупки [WebSocket]
    Game -> Пользователь: Подтверждение покупки и обновление инвентаря
else Внутренней валюты недостаточно
    DB -> Server: Уведомление о недостатке внутренней валюты
    Server -> Game: Уведомление о недостатке внутренней валюты [WebSocket]
    Game -> Пользователь: Уведомление о недостатке внутренней валюты
    note right of Пользователь
    Недостаточно валюты для покупки. 
    Пополнить казну можно тут!
    end note
end

note right of Пользователь: Пользователь получает уведомление о статусе покупки
@enduml
