Схема 2
@startuml

skinparam activity {
    BackgroundColor #lavender
}

|Пользователь|
start
:Открыть инвентарь;
:Перейти во вкладку "магия";
:Выбрать кристалл;
:Выбрать действие "улучшить";

|Клиентская игра|
:Объявить начало улучшения;
:Открыть раздел "амуниция";
:Показать предметы для улучшения;

|Пользователь|
:Выбрать предмет;
:Отправка запроса на сервер;

|Игровой сервер|
:Проверить возможность \nулучшения предмета;

while (Улучшение невозможно) is (Нет)
  |Клиентская игра|
  :Уведомить о невозможности улучшения;
  :Вернуться к выбору предмета;
  |Пользователь|
  :Выбрать другой предмет;
  :Отправка запроса на сервер;
  |Игровой сервер|
  :Проверить возможность \nулучшения предмета;
endwhile (Да)
  
|Клиентская игра|
:Предоставить выбор улучшений;
:Запросить подтверждение улучшения;

|Пользователь|
:Подтверждение улучшения?;

if (да) then (да)
  |Игровой сервер|
  :Применить улучшение;
  :Обновить данные предмета;
  :Сохранить изменения;
  |Клиентская игра|
  :Обновить инвентарь;
  :Уведомить об успешном улучшении;
else (нет)
  |Клиентская игра|
  :Отмена улучшения;
  :Возврат в меню "магия";
endif

|Пользователь|
:Получение уведомления \nо статусе улучшения;
stop
@enduml
